[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_EMBEDDING_PROVIDER = "huggingface"
  VITE_LLM_PROVIDER = "google"
  # Add your API keys in Netlify dashboard

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = "max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"