runtime: nodejs18

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 10

env_variables:
  NODE_ENV: production
  GOOGLE_CLOUD_PROJECT_ID: your-project-id
  GOOGLE_CLOUD_BUCKET: ragnarok-documents
  GEMINI_API_KEY: your-gemini-api-key
  FRONTEND_URL: https://your-frontend-url.com

handlers:
- url: /.*
  script: auto
  secure: always

readiness_check:
  path: "/health"
  check_interval_sec: 5

liveness_check:
  path: "/health" 
  check_interval_sec: 30
